//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEventsManagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEvent
    {
        public TblEvent()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public string EventName { get; set; }
        public string Location { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
